version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: rumble
      POSTGRES_USER: rumble
      POSTGRES_PASSWORD: rumble
    volumes:
      - './pgdata:/var/lib/postgresql/data'
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - './.pgadmin:/var/lib/pgadmin'
